const VEHICLE_TYPES = ["BUZZ", "LITE", "RETROFIT"];
const TRACKING = ["SERIAL", "BATCH", "QUANTITY"];
const CATEGORIES = ["ELECTRICAL", "MECHANICAL", "ELECTRONICS", "CONSUMABLE", "DEVELOPMENT", "OTHER"];

const INVENTORY_CLASSES = ["GENERAL", "PRODUCTION", "DEVELOPMENT"]; // what kind of stock it is - separate from TRACKING (how it is counted)
const DEV_SUBCATEGORIES = ["Electrical", "Electronics", "Hardware", "Metal", "Plastic", "Proprietary", "Rubber"];
const DEV_STATUS = ["DRAFT", "ENGINEERING_REVIEW", "APPROVED", "ACTIVE"];

const MS = {
  RECEIVED: "RECEIVED",
  PENDING_INCOMING_QC: "PENDING_INCOMING_QC",
  APPROVED: "APPROVED",
  HOLD: "HOLD",
  REJECTED: "REJECTED",
  REWORK: "REWORK",
  PENDING_RETEST: "PENDING_RETEST",
  QC_REQUIRED: "QC_REQUIRED",
  INSTALLED: "INSTALLED",
  RETURNED_TO_SUPPLIER: "RETURNED_TO_SUPPLIER",
  SCRAPPED: "SCRAPPED",
  LEGACY_UNVERIFIED: "LEGACY_UNVERIFIED",
};

const LOCATION_TYPES = ["STORE", "ZONE", "RACK", "SHELF", "BIN", "RECEIVING", "QC_HOLD", "REJECT", "REWORK", "WIP", "TRANSIT", "VEHICLE", "SCRAP"];
// Only these can hold stock. STORE/ZONE/RACK/SHELF are grouping nodes.
const STOCK_LOCATION_TYPES = ["BIN", "RECEIVING", "QC_HOLD", "REJECT", "REWORK", "WIP", "TRANSIT", "VEHICLE", "SCRAP"];

const TXN = [
  "RECEIPT", "QC_APPROVAL", "QC_REJECTION", "QC_HOLD", "PUT_AWAY", "ISSUE", "HANDOVER",
  "RETURN", "TRANSFER", "INSTALLATION", "REMOVAL", "ADJUSTMENT", "SCRAP", "REWORK", "RETEST",
];

module.exports = { INVENTORY_CLASSES, DEV_SUBCATEGORIES, DEV_STATUS, VEHICLE_TYPES, TRACKING, CATEGORIES, MS, LOCATION_TYPES, STOCK_LOCATION_TYPES, TXN };
